// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoscbmdiruhjsbmitjgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvc2NibWRpcnVoanNibWl0amdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzA5ODAsImV4cCI6MjA1NjkwNjk4MH0.Qq6rtQjT1XZaLGa9rpY-OyHbaRwzKYPKw0o8lj6reHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
